swagger: "2.0"
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: ""
  version: 1.0.11
paths:
  /api/v1/user_retrieve/{email}:
    get:
      summary: "user情報"
      description: "全てのuser情報を返します"
      parameters: 
      - name: "email"
        in: "path"
        description: "取得したいUser情報のemail"
        required: true
        type: "string"
        format: "string"
      responses:
        200:
          description: "成功時のレスポンス"
          schema: 
            type: "object"
            properties: 
              email:
                type: "string"
                format: "string"
              password:
                type: "string"
                format: "string"