#サンプル1 プロジェクトJSON

{
    "project":"サンプルプロジェクト1",
    "projectData":[
        {
            "tasklist_id":"2d9f9d67-661b-4300-9d17-59097ca4ff93",
            "edit":false,
            "status":"waiting",
            "tasklist":[
                {
                    "tasktype":"task",
                    "task":"サンプルタスク"
                },
                {
                    "tasktype":"subtask",
                    "task":"サンプルサブタスク"
                }
            ]
        },
        {
            "tasklist_id":"2d9f9d67-661b-4300-9d17-59097ca4ff94",
            "edit":false,
            "status":"waiting",
            "tasklist":[
                {
                    "tasktype":"task",
                    "task":"サンプルタスク"
                },
                {
                    "tasktype":"subtask",
                    "task":"サンプルサブタスク"
                }
            ]
        } 
    ]
}
